package sample.ws.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.2 2022-06-28T17:39:54.716+08:00 Generated source
 * version: 3.5.2
 *
 */
@WebService(targetNamespace = "http://service.ws.sample/", name = "Hello")
@XmlSeeAlso({ObjectFactory.class})
public interface Hello {

  @WebMethod(action = "urn:SayHello")
  @RequestWrapper(localName = "sayHello", targetNamespace = "http://service.ws.sample/",
      className = "sample.ws.service.SayHello")
  @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://service.ws.sample/",
      className = "sample.ws.service.SayHelloResponse")
  @WebResult(name = "return", targetNamespace = "")
  public java.lang.String sayHello(

      @WebParam(name = "myname", targetNamespace = "") java.lang.String myname);
}
