
package sample.ws.service;

/**
 * Please modify this class to meet your needs This class is not complete
 */

import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.BindingProvider;

/**
 * This class was generated by Apache CXF 3.5.2 2022-06-28T17:39:54.652+08:00 Generated source
 * version: 3.5.2
 *
 */
public final class Hello_HelloPort_Client {

  private static final Logger LOG = Logger.getLogger(Hello_HelloPort_Client.class.getName());
  
  private static final QName SERVICE_NAME = new QName("http://service.ws.sample/", "HelloService");

  private Hello_HelloPort_Client() {}

  public static void run(String endpoint, String username, String password) throws java.lang.Exception {
    URL wsdlURL = HelloService.WSDL_LOCATION;
    HelloService ss = new HelloService(wsdlURL, SERVICE_NAME);
    Hello port = ss.getHelloPort();
    
    BindingProvider bp = (BindingProvider) port;
    bp.getRequestContext().put(BindingProvider.ENDPOINT_ADDRESS_PROPERTY, endpoint);
    bp.getRequestContext().put(BindingProvider.USERNAME_PROPERTY, username);
    bp.getRequestContext().put(BindingProvider.PASSWORD_PROPERTY, password);
    
    LOG.info("Invoking sayHello...");
    java.lang.String _sayHello_myname = "greeter-" + String.valueOf(System.currentTimeMillis());
    java.lang.String _sayHello__return = port.sayHello(_sayHello_myname);
    LOG.info("sayHello.result=" + _sayHello__return);
  }

}
