
package sample.ws.service;

/**
 * Please modify this class to meet your needs This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.5.2 2022-06-28T17:39:54.652+08:00 Generated source
 * version: 3.5.2
 *
 */
public final class Hello_HelloPort_Client {

  private static final QName SERVICE_NAME = new QName("http://service.ws.sample/", "HelloService");

  private Hello_HelloPort_Client() {}

  public static void main(String args[]) throws java.lang.Exception {
    URL wsdlURL = HelloService.WSDL_LOCATION;
    if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
      File wsdlFile = new File(args[0]);
      try {
        if (wsdlFile.exists()) {
          wsdlURL = wsdlFile.toURI().toURL();
        } else {
          wsdlURL = new URL(args[0]);
        }
      } catch (MalformedURLException e) {
        e.printStackTrace();
      }
    }

    HelloService ss = new HelloService(wsdlURL, SERVICE_NAME);
    Hello port = ss.getHelloPort();
    {
      System.out.println("Invoking sayHello...");
      java.lang.String _sayHello_myname = "greeter-"+String.valueOf(System.currentTimeMillis());
      java.lang.String _sayHello__return = port.sayHello(_sayHello_myname);
      System.out.println("sayHello.result=" + _sayHello__return);
    }
    System.exit(0);
  }

}
